version: "3"

services:
  ##########################################
  # Overrides for oada-core services:
  ##########################################

  # Add ourselves to yarn to do yarn install
  yarn:
    volumes:
      - ./services-available/abalonemail:/code/abalonemail

  # Add ourselves to admin container:
  admin:
    volumes:
      - ./services-available/abalonemail:/code/abalonemail


  ###############################################
  # This service's definition:
  ###############################################
  abalonemail:
    depends_on:
      - startup
    build:
      context: ./services-available/abalonemail
    container_name: abalonemail
    restart: always
    networks:
      - http_net
      - startup_net
      - arango_net
    volumes:
      - ./services-available/abalonemail:/code/abalonemail
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED
      - NODE_ENV=${NODE_ENV:-development}
      - DEBUG

